name: Build App
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

env:
  APP_NAME: ${{ github.event.repository.name }}

jobs:
  build:
    name: Build (OpenBK7238, default, apt)
    runs-on: ubuntu-22.04
    steps:
      - name: Source checkout
        uses: actions/checkout@v4

      - name: Install arm-none-eabi-gcc
        run: |
          curl -sL https://raw.githubusercontent.com/ilikenwf/apt-fast/master/quick-install.sh | sudo bash
          sudo apt-get update
          sudo apt-fast install -y gcc-arm-none-eabi

      - name: Set build version
        id: ver
        run: |
          echo "version=${GITHUB_REF_NAME}_$(git rev-parse --short=12 HEAD)" >> $GITHUB_OUTPUT

      - name: Run make
        run: make APP_VERSION=${{ steps.ver.outputs.version }} APP_NAME=OpenBK7238 VARIANT="default" OpenBK7238

      - name: Save build assets
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APP_NAME }}_${{ steps.ver.outputs.version }}_OpenBK7238
          path: |
            output/${{ steps.ver.outputs.version }}/OpenBK7238_UA_${{ steps.ver.outputs.version }}.bin
            output/${{ steps.ver.outputs.version }}/OpenBK7238_UG_${{ steps.ver.outputs.version }}.bin
            output/${{ steps.ver.outputs.version }}/OpenBK7238_UG_${{ steps.ver.outputs.version }}.img
            output/${{ steps.ver.outputs.version }}/OpenBK7238_QIO_${{ steps.ver.outputs.version }}.bin
            output/${{ steps.ver.outputs.version }}/OpenBK7238_${{ steps.ver.outputs.version }}.rbl
            output/${{ steps.ver.outputs.version }}/OpenBK7238_${{ steps.ver.outputs.version }}.img
            output/${{ steps.ver.outputs.version }}/OpenBK7238_${{ steps.ver.outputs.version }}.bin
            output/${{ steps.ver.outputs.version }}/OpenBK7238_${{ steps.ver.outputs.version }}.fls
            output/${{ steps.ver.outputs.version }}/OpenBK7238_${{ steps.ver.outputs.version }}_ota.img
            output/${{ steps.ver.outputs.version }}/OpenBK7238_${{ steps.ver.outputs.version }}_gz.img
            output/${{ steps.ver.outputs.version }}/OpenBK7238_${{ steps.ver.outputs.version }}_OTA.bin
            output/${{ steps.ver.outputs.version }}/OpenBK7238_${{ steps.ver.outputs.version }}_OTA.bin.xz
            output/${{ steps.ver.outputs.version }}/OpenBK7238_${{ steps.ver.outputs.version }}_OTA.bin.xz.ota
          if-no-files-found: warn
